### ISSUE TITLE
Tesla addon

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/elixir-templates#113]
## Why

So we don't need to setup Tesla manually https://hexdocs.pm/tesla/readme.html

## Who Benefits?

Elixir developer

**Comment by hanam1ni** [comment]
@andyduong1920 I think we shouldn't specify the HTTP client to the template because there are few options for HTTP client libraries (Also, there is [discussion here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588)) and to set up the HTTP client is quite simple. 

So we can avoid having too many addons in the future and give flexibility to the template. What do you think? 💭

**Comment by andyduong1920** [comment]
We can make it as an OPTIONAL addon @hanam1ni , something like

```
Would you like to install HTTP client? Pick one.
1. Tesla
2. HTTPPoison
3. ....
```

**Comment by byhbt** [comment]
The issue is migrated to the Discussions section: https://github.com/nimblehq/elixir-templates/discussions/274
