### ISSUE TITLE
Do not log the Mix info on Test ENV

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/elixir-templates#231]
## Why

The log file is too large and it hard to debug the issue

![image](https://user-images.githubusercontent.com/11751745/172983732-abc46b87-2bcd-48cd-bbbf-ac2be52613b0.png)

## Who Benefits?

Maintainer

**Comment by nvminhtue** [comment]
@byhbt @andyduong1920 
The root cause belonged to the `deps/phoenix/lib/mix/phoenix.ex` module.

Take an example of `copy_from` which uses the `Mix.Generator.create_file` function without passing the option `quiet` -> That leads to showing the unexpected logs as reported.

![image](https://user-images.githubusercontent.com/42540264/198230039-ff9a049a-8469-4294-ad87-2829187396b0.png)

![image](https://user-images.githubusercontent.com/42540264/198230891-9f46b42c-997b-454a-8c5f-1d7a21b6ec7e.png)


No public opts in `copy_from` allow us to set the `quiet` logs, so it can not fix IMO.

What do you think?

**Comment by andyduong1920** [comment]
Got it @nvminhtue, we can't fix this as some logs come from the Phoenix itself, we can close this comment now cc @byhbt
